export const INITIAL_FEATURES = [
  {
    key: "beast-mode-drip",
    label: "Beast Mode Drip",
    description: "Trigger the Beast Mode Drip campaign",
    pillar: "recruit",
    type: "smart-form",
    href: "/dashboard/recruit/beast-mode-drip",
    icon: "zap",
    isActive: true,
    sortOrder: 10,
  },
  {
    key: "field-trainer",
    label: "Field Trainer",
    description: "Access field training resources",
    pillar: "train",
    type: "page",
    href: "/dashboard/train/field-trainer",
    icon: "graduationCap",
    isActive: true,
    sortOrder: 20,
  },
  {
    key: "onboarding-drip",
    label: "Onboarding Drip",
    description: "Manage onboarding drip campaigns",
    pillar: "team",
    type: "smart-form",
    href: "/dashboard/team/onboarding-drip",
    icon: "users",
    isActive: true,
    sortOrder: 30,
  },
  {
    key: "resource-hub",
    label: "Resource Hub",
    description: "Centralized resources and documents",
    pillar: "account",
    type: "page",
    href: "/dashboard/account/resource-hub",
    icon: "library",
    isActive: true,
    sortOrder: 40,
  },
  {
    key: "agent-gradebook",
    label: "Agent Gradebook",
    description: "Track and manage agent performance",
    pillar: "sell",
    type: "iframe",
    href: "/dashboard/sell/agent-gradebook",
    defaultEmbedUrl: "https://example.com/gradebook",
    icon: "barChart",
    isActive: true,
    sortOrder: 50,
  },
] as const;
